### ISSUE TITLE
Ещё хорошие радио

### ISSUE THREAD

**Issue by ruLait** [Anonym-tsk/chrome-online-radio#28]
###### Радио ULTRA

Сайт - http://radioultra.ru/
Лого - http://player.radioultra.ru/images/logos/ultra.jpg
Поток 128 - http://nashe2.hostingradio.ru/ultra-128.mp3
Поток 192 - http://nashe1.hostingradio.ru/ultra-192.mp3
###### Говорит Москва

Сайт - http://govoritmoskva.ru/
Лого - https://i.imgur.com/R6mflEe.png
Поток 32 - http://video.govoritmoskva.ru:8880/ru32.mp3
Поток 64 - http://video.govoritmoskva.ru:8880/ru64.mp3
Поток 96 - http://video.govoritmoskva.ru:8880/rufm_m.mp3
###### Радио Анонимус _(опционально)_

Сайт - http://anon.fm/
Лого - http://anon.fm/imgs/logos/2.png
Поток 64 - http://anon.fm:8000/radio-low
Поток 192 - http://anon.fm:8000/radio
###### MADFM _(опционально)_

Сайт - http://mad.pub/
Лого - http://mad.pub/images/logo.png
Поток 128 - http://mad.pub:8000/live

**Comment by Anonym-tsk** [comment]
Добавим, спасибо.
