### ISSUE TITLE
Translation and suggestions

### ISSUE THREAD

**Issue by ylzhan** [Anonym-tsk/chrome-online-radio#30]
Hello,

Nice extension. Thanks for your work.

If you want to integrate, I translated the extension in French: [messages.txt](https://github.com/Anonym-tsk/chrome-online-radio/files/573593/messages.txt)

Note: "Online Radio" is "Radio en ligne" if translated.

Four suggestions:

- Get the tag (artist, song, cover) from the stream.
- Allow to definitely delete (not just disable) the default stations. 
- Allow also multiple selections when disabling/removing stations.
- Add stations from other countries based on the download statistics of your extension.

Here is a list of streams (aac/mp3) for stations in France:
http://fluxradios.blogspot.fr/p/flux-radios-francaise.html

**Comment by Anonym-tsk** [comment]
Thank you.
I'll add translations.

**Comment by ylzhan** [comment]
@Anonym-tsk 

You forget an S here. You need to paste this:

```
+  "user_stations": {
+    "message": "Stations personnalisées"
```

**Comment by Anonym-tsk** [comment]
@ylzhan thank you

**Comment by Anonym-tsk** [comment]
@ylzhan 
 * I cannot get the tag from the stream. It's impossible on JS currently.
 * I redesigned the stations page and now deleted stations in other list.
